### ISSUE TITLE
Build fails on AppVeyor/Windows

### ISSUE THREAD

**Issue by craigfowler** [csf-dev/CSF.Screenplay#115]
[Here is a failed build], it needs investigation and fixing.  It looks like it might be something to do with the testing web application; Selenium can't find anything on any of its web pages, so maybe it's not coming up right.

[Here is a failed build]: https://ci.appveyor.com/project/craigfowler/csf-screenplay/build/master-200

**Comment by craigfowler** [comment]
This might have something to do with the `web.config` file in the testing website. It has the `System.Dynamic` binding with the key token for Linux/mono and not Windows/.NET.

This should be the first item of investigation.

**Comment by craigfowler** [comment]
That commit above has helped but not completely solved the problem:

```
1) Failed : CSF.Screenplay.JsonApis.Tests.ExecuteAJsonApiTests.Using_CheckData_does_not_raise_exception_for_valid_data([Screenplay scenario:709a83fb-a830-48ce-8ddf-e9bcf4b2f1f9])
  Expected: No Exception to be thrown
  But was:  <System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StreamContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.ReadAsStringAsync()
   at CSF.Screenplay.JsonApis.Abilities.ConsumeJsonWebServices.AssertThatResultIsSuccess(HttpResponseMessage result, TimeSpan timeout) in C:\projects\csf-screenplay\CSF.Screenplay.JsonApis\Abilities\ConsumeJsonWebServices.cs:line 66
   at CSF.Screenplay.JsonApis.Abilities.ConsumeJsonWebServices.GetResponse(IProvidesInvocationDetails invocationDetails) in C:\projects\csf-screenplay\CSF.Screenplay.JsonApis\Abilities\ConsumeJsonWebServices.cs:line 53
   at CSF.Screenplay.JsonApis.Abilities.ConsumeJsonWebServices.Execute(IProvidesInvocationDetails invocationDetails) in C:\projects\csf-screenplay\CSF.Screenplay.JsonApis\Abilities\ConsumeJsonWebServices.cs:line 26
   at CSF.Screenplay.JsonApis.Actions.ExecuteApi.PerformAs(IPerformer actor) in C:\projects\csf-screenplay\CSF.Screenplay.JsonApis\Actions\ExecuteApi.cs:line 21
   at CSF.Screenplay.Performables.Performable.CSF.Screenplay.Performables.IPerformable.PerformAs(IPerformer actor) in C:\projects\csf-screenplay\CSF.Screenplay\Performables\Performable.cs:line 41
   at CSF.Screenplay.Actors.Actor.Perform(IPerformable performable) in C:\projects\csf-screenplay\CSF.Screenplay\Actors\Actor.cs:line 112
   at CSF.Screenplay.Actors.Actor.CSF.Screenplay.Actors.IWhenActor.AttemptsTo(IPerformable performable) in C:\projects\csf-screenplay\CSF.Screenplay\Actors\Actor.cs:line 367
   at CSF.Screenplay.JsonApis.Tests.ExecuteAJsonApiTests.<>c__DisplayClass2_0.<Using_CheckData_does_not_raise_exception_for_valid_data>b__0() in C:\projects\csf-screenplay\Tests\CSF.Screenplay.JsonApis.Tests\ExecuteAJsonApiTests.cs:line 49
   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
at CSF.Screenplay.JsonApis.Tests.ExecuteAJsonApiTests.Using_CheckData_does_not_raise_exception_for_valid_data(IScreenplayScenario scenario) in C:\projects\csf-screenplay\Tests\CSF.Screenplay.JsonApis.Tests\ExecuteAJsonApiTests.cs:line 49
2) Failed : CSF.Screenplay.JsonApis.Tests.ExecuteAJsonApiTests.Using_CheckData_raises_exception_for_invalid_data([Screenplay scenario:06db7fe6-dc08-4526-9d60-7a9ee44b98b1])
  Expected: instance of <CSF.Screenplay.JsonApis.JsonApiException>
  But was:  <System.ObjectDisposedException>
at CSF.Screenplay.JsonApis.Tests.ExecuteAJsonApiTests.Using_CheckData_raises_exception_for_invalid_data(IScreenplayScenario scenario) in C:\projects\csf-screenplay\Tests\CSF.Screenplay.JsonApis.Tests\ExecuteAJsonApiTests.cs:line 60
```
